version: "3"
services:
  go-docker:
    container_name: go_docker
    build: ./
    ports:
      - '9120:9120'
    volumes:
      - ./:/app
    restart: unless-stopped
    depends_on: 
      - cache # This service depends on redis. Start that first.
      - postgres
    

  cache:
    container_name: go_redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data:cached
    restart: "on-failure"
  postgres:
    container_name: go_postgres
    image: postgres:10.5
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/run/postgresql/data:cached

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local

  